2025-02-18 15:18:47,026 INFO    MainThread:12940 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2025-02-18 15:18:47,027 INFO    MainThread:12940 [wandb_setup.py:_flush():76] Configure stats pid to 12940
2025-02-18 15:18:47,027 INFO    MainThread:12940 [wandb_setup.py:_flush():76] Loading settings from /home/t/.config/wandb/settings
2025-02-18 15:18:47,027 INFO    MainThread:12940 [wandb_setup.py:_flush():76] Loading settings from /home/t/workspace/AGI/THBI/sae_demo/wandb/settings
2025-02-18 15:18:47,027 INFO    MainThread:12940 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'entity': 'electrixoul-tsinghua-university'}
2025-02-18 15:18:47,027 INFO    MainThread:12940 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-02-18 15:18:47,028 INFO    MainThread:12940 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'test_wandb.py', 'program_abspath': '/home/t/workspace/AGI/THBI/sae_demo/test_wandb.py', 'program': '/home/t/workspace/AGI/THBI/sae_demo/test_wandb.py'}
2025-02-18 15:18:47,028 INFO    MainThread:12940 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-02-18 15:18:47,028 INFO    MainThread:12940 [wandb_init.py:_log_setup():521] Logging user logs to /home/t/workspace/AGI/THBI/sae_demo/wandb/run-20250218_151847-6s6t2b6j/logs/debug.log
2025-02-18 15:18:47,028 INFO    MainThread:12940 [wandb_init.py:_log_setup():522] Logging internal logs to /home/t/workspace/AGI/THBI/sae_demo/wandb/run-20250218_151847-6s6t2b6j/logs/debug-internal.log
2025-02-18 15:18:47,028 INFO    MainThread:12940 [wandb_init.py:init():561] calling init triggers
2025-02-18 15:18:47,028 INFO    MainThread:12940 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2025-02-18 15:18:47,029 INFO    MainThread:12940 [wandb_init.py:init():611] starting backend
2025-02-18 15:18:47,029 INFO    MainThread:12940 [wandb_init.py:init():615] setting up manager
2025-02-18 15:18:47,033 INFO    MainThread:12940 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-02-18 15:18:47,034 INFO    MainThread:12940 [wandb_init.py:init():623] backend started and connected
2025-02-18 15:18:47,037 INFO    MainThread:12940 [wandb_init.py:init():715] updated telemetry
2025-02-18 15:18:47,040 INFO    MainThread:12940 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2025-02-18 15:18:48,180 ERROR   MainThread:12940 [wandb_init.py:init():774] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-02-18 15:18:48,625 ERROR   MainThread:12940 [wandb_init.py:init():1199] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/home/t/anaconda3/envs/sae/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/t/anaconda3/envs/sae/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-02-18 15:18:49,631 WARNING MsgRouterThr:12940 [router.py:message_loop():77] message_loop has been closed
