2025-04-29 18:06:15,243 INFO    MainThread:225774 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2025-04-29 18:06:15,243 INFO    MainThread:225774 [wandb_setup.py:_flush():76] Configure stats pid to 225774
2025-04-29 18:06:15,243 INFO    MainThread:225774 [wandb_setup.py:_flush():76] Loading settings from /home/t/.config/wandb/settings
2025-04-29 18:06:15,243 INFO    MainThread:225774 [wandb_setup.py:_flush():76] Loading settings from /home/t/workspace/lab_work/sae_demo/wandb/settings
2025-04-29 18:06:15,244 INFO    MainThread:225774 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-04-29 18:06:15,244 INFO    MainThread:225774 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-04-29 18:06:15,244 INFO    MainThread:225774 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'wandb_test_minimal.py', 'program_abspath': '/home/t/workspace/lab_work/sae_demo/wandb_test_minimal.py', 'program': '/home/t/workspace/lab_work/sae_demo/wandb_test_minimal.py'}
2025-04-29 18:06:15,244 INFO    MainThread:225774 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-04-29 18:06:15,244 INFO    MainThread:225774 [wandb_init.py:_log_setup():521] Logging user logs to /home/t/workspace/lab_work/sae_demo/wandb/run-20250429_180615-79u8rv96/logs/debug.log
2025-04-29 18:06:15,244 INFO    MainThread:225774 [wandb_init.py:_log_setup():522] Logging internal logs to /home/t/workspace/lab_work/sae_demo/wandb/run-20250429_180615-79u8rv96/logs/debug-internal.log
2025-04-29 18:06:15,244 INFO    MainThread:225774 [wandb_init.py:init():561] calling init triggers
2025-04-29 18:06:15,244 INFO    MainThread:225774 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'test_type': 'connection_verification', 'timestamp': '2025-04-29_18-06-14'}
2025-04-29 18:06:15,244 INFO    MainThread:225774 [wandb_init.py:init():611] starting backend
2025-04-29 18:06:15,244 INFO    MainThread:225774 [wandb_init.py:init():615] setting up manager
2025-04-29 18:06:15,247 INFO    MainThread:225774 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-29 18:06:15,248 INFO    MainThread:225774 [wandb_init.py:init():623] backend started and connected
2025-04-29 18:06:15,252 INFO    MainThread:225774 [wandb_init.py:init():715] updated telemetry
2025-04-29 18:06:15,255 INFO    MainThread:225774 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2025-04-29 18:06:15,856 ERROR   MainThread:225774 [wandb_init.py:init():774] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-04-29 18:06:16,120 ERROR   MainThread:225774 [wandb_init.py:init():1199] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/home/t/anaconda3/envs/sae_eeg/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
  File "/home/t/anaconda3/envs/sae_eeg/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-04-29 18:06:17,123 WARNING MsgRouterThr:225774 [router.py:message_loop():77] message_loop has been closed
