2025-04-29 18:07:56,569 INFO    MainThread:226689 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2025-04-29 18:07:56,569 INFO    MainThread:226689 [wandb_setup.py:_flush():76] Configure stats pid to 226689
2025-04-29 18:07:56,569 INFO    MainThread:226689 [wandb_setup.py:_flush():76] Loading settings from /home/t/.config/wandb/settings
2025-04-29 18:07:56,569 INFO    MainThread:226689 [wandb_setup.py:_flush():76] Loading settings from /home/t/workspace/lab_work/sae_demo/wandb/settings
2025-04-29 18:07:56,569 INFO    MainThread:226689 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***', 'entity': 'electrixoul'}
2025-04-29 18:07:56,569 INFO    MainThread:226689 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-04-29 18:07:56,569 INFO    MainThread:226689 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'wandb_personal_test.py', 'program_abspath': '/home/t/workspace/lab_work/sae_demo/wandb_personal_test.py', 'program': '/home/t/workspace/lab_work/sae_demo/wandb_personal_test.py'}
2025-04-29 18:07:56,569 INFO    MainThread:226689 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-04-29 18:07:56,569 INFO    MainThread:226689 [wandb_init.py:_log_setup():521] Logging user logs to /home/t/workspace/lab_work/sae_demo/wandb/run-20250429_180756-0yfcs62e/logs/debug.log
2025-04-29 18:07:56,569 INFO    MainThread:226689 [wandb_init.py:_log_setup():522] Logging internal logs to /home/t/workspace/lab_work/sae_demo/wandb/run-20250429_180756-0yfcs62e/logs/debug-internal.log
2025-04-29 18:07:56,569 INFO    MainThread:226689 [wandb_init.py:init():561] calling init triggers
2025-04-29 18:07:56,569 INFO    MainThread:226689 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'test_type': 'direct_api_key_test', 'timestamp': '2025-04-29_18-07-55'}
2025-04-29 18:07:56,569 INFO    MainThread:226689 [wandb_init.py:init():611] starting backend
2025-04-29 18:07:56,569 INFO    MainThread:226689 [wandb_init.py:init():615] setting up manager
2025-04-29 18:07:56,572 INFO    MainThread:226689 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-29 18:07:56,572 INFO    MainThread:226689 [wandb_init.py:init():623] backend started and connected
2025-04-29 18:07:56,576 INFO    MainThread:226689 [wandb_init.py:init():715] updated telemetry
2025-04-29 18:07:56,578 INFO    MainThread:226689 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2025-04-29 18:07:57,370 ERROR   MainThread:226689 [wandb_init.py:init():774] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-04-29 18:07:57,654 ERROR   MainThread:226689 [wandb_init.py:init():1199] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/home/t/anaconda3/envs/sae_eeg/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
  File "/home/t/anaconda3/envs/sae_eeg/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-04-29 18:07:58,657 WARNING MsgRouterThr:226689 [router.py:message_loop():77] message_loop has been closed
